spring.application.name=ticketfu

# 1. Cambiamos el puerto para evitar el error de 'Address already in use'
server.port=8080

# Configuración de Spring Security
spring.security.user.name=ismael
spring.security.user.password=1234

# Configuración de Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketfu_db
spring.datasource.username=ticketfu_user
spring.datasource.password=1234

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 2. Desactivar temporalmente la autoconfiguración de Spring AI para que no rompa Swagger
spring.ai.openai.chat.enabled=false
# O coloca una clave placeholder válida si requiere el String:
spring.ai.openai.api-key=sk-placeholder-key-to-avoid-swagger-error

# JWT Config
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Swagger Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.ismael.ticketfu.controller